# Generated by Django 4.2.7 on 2023-11-16 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_item_discount1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='discount1',
        ),
    ]
