# Generated by Django 4.2.7 on 2023-11-19 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_item_discount1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Burger', 'Burger'), ('Pizza', 'Pizza'), ('Pasta', 'Pasta'), ('Fries', 'Fries')], max_length=10),
        ),
    ]
