# Generated by Django 4.2.7 on 2023-11-19 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_item_discount'),
        ('home', '0004_alter_item_category'),
    ]

    operations = [
    ]
