# Generated by Django 4.2.7 on 2023-11-27 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_lineitem_guest_alter_lineitem_user'),
        ('home', '0006_alter_item_image'),
    ]

    operations = [
    ]
