# Generated by Django 4.2.7 on 2023-12-05 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_lineitem_title'),
        ('home', '0009_alter_item_image'),
    ]

    operations = [
    ]
