# Generated by Django 4.2.7 on 2023-12-06 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_merge_0008_lineitem_title_0009_alter_item_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineitem',
            name='title',
        ),
    ]
