# Generated by Django 4.2.7 on 2023-12-06 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_lineitem_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitem',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
